// src/components/Feedback/ReviewAnalysis.js - Beautiful Neumorphic Design
import React, { useState } from 'react';
import { saveReview } from '../../services/reviewService';
import { getUserPoints, awardPoints } from '../../services/pointsService';
import { useAuth } from '../../contexts/AuthContext';

const ReviewAnalysis = ({ reviewData, onSaveSuccess, onStartOver, placeId }) => {
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState(null);
  const [showShareModal, setShowShareModal] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const [showAnalysis, setShowAnalysis] = useState(true);
  
  const { currentUser } = useAuth();

  // Get authenticated user
  const getAuthenticatedUser = () => {
    return currentUser;
  };

  // Save review function
  const handleSaveReview = async () => {
    const user = getAuthenticatedUser();
    if (!user) {
      setError('Please log in to save your review');
      return;
    }

    setSaving(true);
    setError(null);

    try {
      // Save the review
      const saveResult = await saveReview(reviewData, user);
      
      if (saveResult.success) {
        // Award points
        try {
          await awardPoints(user.uid, 10, 'review_submission');
        } catch (pointsError) {
          console.warn('Points award failed:', pointsError);
        }
        
        setSaved(true);
        if (onSaveSuccess) onSaveSuccess();
        
        // Auto-show sharing after save
        setTimeout(() => {
          setShowShareModal(true);
        }, 1000);
      } else {
        throw new Error(saveResult.error || 'Failed to save review');
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  };

  // Render star rating with neumorphic design
  const renderStars = (score) => {
    const stars = [];
    const fullStars = Math.floor(score);
    const hasHalfStar = score % 1 !== 0;
    
    for (let i = 0; i < fullStars; i++) {
      stars.push('⭐');
    }
    if (hasHalfStar) {
      stars.push('✨');
    }
    
    return stars;
  };

  // Get sentiment color and message
  const getSentimentInfo = (score) => {
    if (score >= 4.5) return { color: '#10b981', message: 'Excellent Experience!', emoji: '🌟' };
    if (score >= 4) return { color: '#22c55e', message: 'Great Experience!', emoji: '😊' };
    if (score >= 3) return { color: '#f59e0b', message: 'Good Experience', emoji: '😐' };
    if (score >= 2) return { color: '#ef4444', message: 'Below Average', emoji: '😕' };
    return { color: '#dc2626', message: 'Poor Experience', emoji: '😞' };
  };

  // Generate formatted review for copying
  const generateFormattedReview = () => {
    const sentimentInfo = getSentimentInfo(reviewData.sentiment_score);
    return `🍽️ Restaurant Review (${sentimentInfo.message})

${reviewData.summary}

🍴 Food Quality: ${reviewData.food_quality}

👥 Service: ${reviewData.service}

🏪 Atmosphere: ${reviewData.atmosphere}

🎵 Music & Entertainment: ${reviewData.music_and_entertainment}

⭐ Overall Rating: ${renderStars(reviewData.sentiment_score).join('')} (${reviewData.sentiment_score}/5)

${reviewData.specific_points?.length > 0 ? 
  `🎯 Key Points:
${reviewData.specific_points.map(point => `• ${point}`).join('\n')}` : ''}

${reviewData.improvement_suggestions?.length > 0 ? 
  `💡 Suggestions for Improvement:
${reviewData.improvement_suggestions.map(suggestion => `• ${suggestion}`).join('\n')}` : ''}

Generated by Restaurant Review AI ✨`;
  };

  // Copy to clipboard
  const handleCopyReview = async () => {
    try {
      const reviewText = generateFormattedReview();
      await navigator.clipboard.writeText(reviewText);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Share modal component
  const ShareModal = () => {
    if (!showShareModal) return null;

    return (
      <div style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
        padding: '1rem'
      }}>
        <div style={{
          background: 'var(--neuro-bg, #e0e0e0)',
          borderRadius: '30px',
          padding: '2.5rem',
          maxWidth: '500px',
          width: '100%',
          position: 'relative',
          boxShadow: `
            20px 20px 40px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
            -20px -20px 40px var(--neuro-shadow-light, rgba(255,255,255,0.9)),
            inset 2px 2px 4px var(--neuro-shadow-inner-light, rgba(255,255,255,0.5)),
            inset -2px -2px 4px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.1))
          `
        }}>
          <button
            onClick={() => setShowShareModal(false)}
            style={{
              position: 'absolute',
              top: '1rem',
              right: '1rem',
              width: '40px',
              height: '40px',
              border: 'none',
              borderRadius: '50%',
              background: 'var(--neuro-bg, #e0e0e0)',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '18px',
              color: 'var(--neuro-text-secondary, #5a6c7d)',
              boxShadow: `
                6px 6px 12px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
                -6px -6px 12px var(--neuro-shadow-light, rgba(255,255,255,0.9))
              `,
              transition: 'all 0.3s ease'
            }}
            onMouseOver={(e) => {
              e.target.style.boxShadow = `
                inset 3px 3px 6px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                inset -3px -3px 6px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
              `;
            }}
            onMouseOut={(e) => {
              e.target.style.boxShadow = `
                6px 6px 12px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
                -6px -6px 12px var(--neuro-shadow-light, rgba(255,255,255,0.9))
              `;
            }}
          >
            ✕
          </button>

          <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
            <div style={{ fontSize: '48px', marginBottom: '1rem' }}>📤</div>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: 'bold',
              color: 'var(--neuro-text-primary, #2c3e50)',
              marginBottom: '0.5rem'
            }}>
              Share Your Review
            </h2>
            <p style={{
              color: 'var(--neuro-text-secondary, #5a6c7d)',
              fontSize: '0.875rem'
            }}>
              Copy your formatted review to share on social media
            </p>
          </div>

          <button
            onClick={handleCopyReview}
            style={{
              width: '100%',
              padding: '1rem 2rem',
              border: 'none',
              borderRadius: '20px',
              background: copySuccess ? '#10b981' : 'var(--neuro-bg, #e0e0e0)',
              color: copySuccess ? 'white' : 'var(--neuro-text-primary, #2c3e50)',
              fontSize: '1rem',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '0.5rem',
              transition: 'all 0.3s ease',
              boxShadow: copySuccess ? 'none' : `
                8px 8px 16px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
                -8px -8px 16px var(--neuro-shadow-light, rgba(255,255,255,0.9))
              `
            }}
          >
            {copySuccess ? '✅ Copied!' : '📋 Copy Formatted Review'}
          </button>
        </div>
      </div>
    );
  };

  // Main render
  if (!reviewData) {
    return (
      <div style={{
        background: 'var(--neuro-bg, #e0e0e0)',
        minHeight: '100vh',
        padding: '2rem 1rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}>
        <div style={{
          background: 'var(--neuro-bg, #e0e0e0)',
          borderRadius: '30px',
          padding: '3rem 2rem',
          textAlign: 'center',
          boxShadow: `
            20px 20px 40px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
            -20px -20px 40px var(--neuro-shadow-light, rgba(255,255,255,0.9))
          `
        }}>
          <div style={{ fontSize: '48px', marginBottom: '1rem' }}>🤔</div>
          <h2 style={{
            fontSize: '1.5rem',
            color: 'var(--neuro-text-primary, #2c3e50)',
            marginBottom: '1rem'
          }}>
            No Review Data
          </h2>
          <p style={{
            color: 'var(--neuro-text-secondary, #5a6c7d)',
            marginBottom: '2rem'
          }}>
            Something went wrong processing your review. Please try again.
          </p>
          <button
            onClick={onStartOver}
            style={{
              padding: '1rem 2rem',
              border: 'none',
              borderRadius: '20px',
              background: 'var(--neuro-bg, #e0e0e0)',
              color: 'var(--neuro-text-primary, #2c3e50)',
              fontSize: '1rem',
              fontWeight: '600',
              cursor: 'pointer',
              boxShadow: `
                8px 8px 16px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
                -8px -8px 16px var(--neuro-shadow-light, rgba(255,255,255,0.9))
              `
            }}
          >
            🔄 Try Again
          </button>
        </div>
      </div>
    );
  }

  const sentimentInfo = getSentimentInfo(reviewData.sentiment_score);

  return (
    <div style={{
      background: 'var(--neuro-bg, #e0e0e0)',
      minHeight: '100vh',
      padding: '2rem 1rem',
      transition: 'all 0.3s ease'
    }}>
      <style jsx>{`
        /* Dark mode support for neumorphic analysis */
        [data-theme="dark"] {
          --neuro-bg: #212121;
          --neuro-shadow-dark: rgb(25, 25, 25);
          --neuro-shadow-light: rgb(60, 60, 60);
          --neuro-shadow-inner-dark: rgb(20, 20, 20);
          --neuro-shadow-inner-light: rgb(55, 55, 55);
          --neuro-text-primary: #e8e8e8;
          --neuro-text-secondary: #b8b8b8;
          --neuro-text-accent: #7c9aff;
        }

        /* Animations */
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-10px); }
        }

        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.8; }
        }

        @keyframes slideInUp {
          from {
            opacity: 0;
            transform: translateY(30px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .analysis-container {
          animation: slideInUp 0.6s ease-out;
        }

        .floating-icon {
          animation: float 3s ease-in-out infinite;
        }

        .pulse-badge {
          animation: pulse 2s infinite;
        }

        /* Responsive design */
        @media (max-width: 768px) {
          .analysis-grid {
            grid-template-columns: 1fr !important;
            gap: 1.5rem !important;
          }
          
          .analysis-header {
            padding: 1.5rem !important;
          }
          
          .category-card {
            padding: 1.5rem !important;
          }
          
          .action-buttons {
            flex-direction: column !important;
            gap: 1rem !important;
          }
        }
      `}</style>

      <div className="analysis-container" style={{
        maxWidth: '1200px',
        margin: '0 auto'
      }}>
        {/* Header Card */}
        <div className="analysis-header" style={{
          background: 'var(--neuro-bg, #e0e0e0)',
          borderRadius: '30px',
          padding: '2.5rem',
          marginBottom: '2rem',
          textAlign: 'center',
          boxShadow: `
            20px 20px 40px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
            -20px -20px 40px var(--neuro-shadow-light, rgba(255,255,255,0.9)),
            inset 2px 2px 4px var(--neuro-shadow-inner-light, rgba(255,255,255,0.5)),
            inset -2px -2px 4px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.1))
          `
        }}>
          <div className="floating-icon" style={{ fontSize: '64px', marginBottom: '1rem' }}>
            {sentimentInfo.emoji}
          </div>
          
          <h1 style={{
            fontSize: '2.5rem',
            fontWeight: '800',
            color: 'var(--neuro-text-primary, #2c3e50)',
            marginBottom: '0.5rem',
            background: `linear-gradient(135deg, ${sentimentInfo.color}, ${sentimentInfo.color}dd)`,
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            backgroundClip: 'text'
          }}>
            Review Analysis Complete!
          </h1>
          
          <p style={{
            fontSize: '1.125rem',
            color: 'var(--neuro-text-secondary, #5a6c7d)',
            marginBottom: '2rem'
          }}>
            Here's your AI-powered feedback breakdown
          </p>

          {/* Sentiment Score Display */}
          <div style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '25px',
            padding: '1.5rem',
            display: 'inline-block',
            boxShadow: `
              inset 8px 8px 16px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
              inset -8px -8px 16px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
            `
          }}>
            <div style={{
              fontSize: '2rem',
              marginBottom: '0.5rem'
            }}>
              {renderStars(reviewData.sentiment_score).join('')}
            </div>
            <div style={{
              fontSize: '1.25rem',
              fontWeight: '700',
              color: sentimentInfo.color
            }}>
              {reviewData.sentiment_score}/5 - {sentimentInfo.message}
            </div>
          </div>
        </div>

        {/* Summary Card */}
        <div style={{
          background: 'var(--neuro-bg, #e0e0e0)',
          borderRadius: '25px',
          padding: '2rem',
          marginBottom: '2rem',
          boxShadow: `
            15px 15px 30px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
            -15px -15px 30px var(--neuro-shadow-light, rgba(255,255,255,0.9))
          `
        }}>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: '1rem',
            marginBottom: '1.5rem'
          }}>
            <div style={{
              width: '50px',
              height: '50px',
              borderRadius: '50%',
              background: 'var(--neuro-bg, #e0e0e0)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '24px',
              boxShadow: `
                inset 6px 6px 12px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                inset -6px -6px 12px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
              `
            }}>
              📝
            </div>
            <h2 style={{
              fontSize: '1.5rem',
              fontWeight: '700',
              color: 'var(--neuro-text-primary, #2c3e50)'
            }}>
              Summary
            </h2>
          </div>
          <p style={{
            fontSize: '1.125rem',
            lineHeight: '1.6',
            color: 'var(--neuro-text-secondary, #5a6c7d)',
            margin: 0
          }}>
            {reviewData.summary}
          </p>
        </div>

        {/* Categories Grid */}
        <div className="analysis-grid" style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: '2rem',
          marginBottom: '2rem'
        }}>
          {/* Food Quality */}
          <div className="category-card" style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '25px',
            padding: '2rem',
            boxShadow: `
              12px 12px 25px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
              -12px -12px 25px var(--neuro-shadow-light, rgba(255,255,255,0.9))
            `,
            transition: 'all 0.3s ease'
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem',
              marginBottom: '1rem'
            }}>
              <div style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                background: 'var(--neuro-bg, #e0e0e0)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '20px',
                boxShadow: `
                  inset 4px 4px 8px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                  inset -4px -4px 8px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
                `
              }}>
                🍽️
              </div>
              <h3 style={{
                fontSize: '1.25rem',
                fontWeight: '600',
                color: 'var(--neuro-text-primary, #2c3e50)',
                margin: 0
              }}>
                Food Quality
              </h3>
            </div>
            <p style={{
              fontSize: '0.95rem',
              lineHeight: '1.5',
              color: 'var(--neuro-text-secondary, #5a6c7d)',
              margin: 0
            }}>
              {reviewData.food_quality}
            </p>
          </div>

          {/* Service */}
          <div className="category-card" style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '25px',
            padding: '2rem',
            boxShadow: `
              12px 12px 25px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
              -12px -12px 25px var(--neuro-shadow-light, rgba(255,255,255,0.9))
            `,
            transition: 'all 0.3s ease'
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem',
              marginBottom: '1rem'
            }}>
              <div style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                background: 'var(--neuro-bg, #e0e0e0)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '20px',
                boxShadow: `
                  inset 4px 4px 8px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                  inset -4px -4px 8px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
                `
              }}>
                👥
              </div>
              <h3 style={{
                fontSize: '1.25rem',
                fontWeight: '600',
                color: 'var(--neuro-text-primary, #2c3e50)',
                margin: 0
              }}>
                Service
              </h3>
            </div>
            <p style={{
              fontSize: '0.95rem',
              lineHeight: '1.5',
              color: 'var(--neuro-text-secondary, #5a6c7d)',
              margin: 0
            }}>
              {reviewData.service}
            </p>
          </div>

          {/* Atmosphere */}
          <div className="category-card" style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '25px',
            padding: '2rem',
            boxShadow: `
              12px 12px 25px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
              -12px -12px 25px var(--neuro-shadow-light, rgba(255,255,255,0.9))
            `,
            transition: 'all 0.3s ease'
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem',
              marginBottom: '1rem'
            }}>
              <div style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                background: 'var(--neuro-bg, #e0e0e0)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '20px',
                boxShadow: `
                  inset 4px 4px 8px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                  inset -4px -4px 8px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
                `
              }}>
                🏪
              </div>
              <h3 style={{
                fontSize: '1.25rem',
                fontWeight: '600',
                color: 'var(--neuro-text-primary, #2c3e50)',
                margin: 0
              }}>
                Atmosphere
              </h3>
            </div>
            <p style={{
              fontSize: '0.95rem',
              lineHeight: '1.5',
              color: 'var(--neuro-text-secondary, #5a6c7d)',
              margin: 0
            }}>
              {reviewData.atmosphere}
            </p>
          </div>

          {/* Music & Entertainment */}
          <div className="category-card" style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '25px',
            padding: '2rem',
            boxShadow: `
              12px 12px 25px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
              -12px -12px 25px var(--neuro-shadow-light, rgba(255,255,255,0.9))
            `,
            transition: 'all 0.3s ease'
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem',
              marginBottom: '1rem'
            }}>
              <div style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                background: 'var(--neuro-bg, #e0e0e0)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '20px',
                boxShadow: `
                  inset 4px 4px 8px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                  inset -4px -4px 8px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
                `
              }}>
                🎵
              </div>
              <h3 style={{
                fontSize: '1.25rem',
                fontWeight: '600',
                color: 'var(--neuro-text-primary, #2c3e50)',
                margin: 0
              }}>
                Music & Entertainment
              </h3>
            </div>
            <p style={{
              fontSize: '0.95rem',
              lineHeight: '1.5',
              color: 'var(--neuro-text-secondary, #5a6c7d)',
              margin: 0
            }}>
              {reviewData.music_and_entertainment}
            </p>
          </div>
        </div>

        {/* Key Points */}
        {reviewData?.specific_points && reviewData.specific_points.length > 0 && (
          <div style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '25px',
            padding: '2rem',
            marginBottom: '2rem',
            boxShadow: `
              15px 15px 30px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
              -15px -15px 30px var(--neuro-shadow-light, rgba(255,255,255,0.9))
            `
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem',
              marginBottom: '1.5rem'
            }}>
              <div style={{
                width: '50px',
                height: '50px',
                borderRadius: '50%',
                background: 'var(--neuro-bg, #e0e0e0)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '24px',
                boxShadow: `
                  inset 6px 6px 12px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                  inset -6px -6px 12px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
                `
              }}>
                🎯
              </div>
              <h2 style={{
                fontSize: '1.5rem',
                fontWeight: '700',
                color: 'var(--neuro-text-primary, #2c3e50)'
              }}>
                Key Points
              </h2>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {reviewData.specific_points.map((point, index) => (
                <div key={index} style={{ 
                  display: 'flex', 
                  alignItems: 'flex-start', 
                  gap: '1rem'
                }}>
                  <div style={{
                    width: '30px',
                    height: '30px',
                    borderRadius: '50%',
                    background: '#3b82f6',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    marginTop: '2px',
                    color: 'white',
                    fontSize: '0.875rem',
                    fontWeight: '600'
                  }}>
                    {index + 1}
                  </div>
                  <p style={{ 
                    fontSize: '0.95rem', 
                    lineHeight: '1.5',
                    color: 'var(--neuro-text-secondary, #5a6c7d)',
                    margin: 0
                  }}>
                    {point}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Improvement Suggestions */}
        {reviewData?.improvement_suggestions && reviewData.improvement_suggestions.length > 0 && (
          <div style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '25px',
            padding: '2rem',
            marginBottom: '2rem',
            boxShadow: `
              15px 15px 30px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
              -15px -15px 30px var(--neuro-shadow-light, rgba(255,255,255,0.9))
            `
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem',
              marginBottom: '1.5rem'
            }}>
              <div style={{
                width: '50px',
                height: '50px',
                borderRadius: '50%',
                background: 'var(--neuro-bg, #e0e0e0)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '24px',
                boxShadow: `
                  inset 6px 6px 12px var(--neuro-shadow-inner-dark, rgba(0,0,0,0.2)),
                  inset -6px -6px 12px var(--neuro-shadow-inner-light, rgba(255,255,255,0.8))
                `
              }}>
                💡
              </div>
              <h2 style={{
                fontSize: '1.5rem',
                fontWeight: '700',
                color: 'var(--neuro-text-primary, #2c3e50)'
              }}>
                Suggestions for Improvement
              </h2>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {reviewData.improvement_suggestions.map((suggestion, index) => (
                <div key={index} style={{ 
                  display: 'flex', 
                  alignItems: 'flex-start', 
                  gap: '1rem'
                }}>
                  <div style={{
                    width: '30px',
                    height: '30px',
                    borderRadius: '50%',
                    background: '#f59e0b',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    marginTop: '2px',
                    color: 'white',
                    fontSize: '16px'
                  }}>
                    💡
                  </div>
                  <p style={{ 
                    fontSize: '0.95rem', 
                    lineHeight: '1.5',
                    color: 'var(--neuro-text-secondary, #5a6c7d)',
                    margin: 0
                  }}>
                    {suggestion}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Error Display */}
        {error && (
          <div style={{
            background: 'var(--neuro-bg, #e0e0e0)',
            borderRadius: '20px',
            padding: '1.5rem',
            marginBottom: '2rem',
            border: '2px solid #ef4444',
            textAlign: 'center',
            boxShadow: `
              10px 10px 20px var(--neuro-shadow-dark, rgba(0,0,0,0.3)),
              -10px -10px 20px var(--neuro-shadow-light, rgba(255,255,255,0.9))
            `
          }}>
            <div style={{ fontSize: '32px', marginBottom: '1rem' }}>⚠️</div>
            <p style={{
              color: '#ef4444',
              fontSize: '0.875rem',
              fontWeight: '600',
              margin: 0
            }}>
              {error}
            </p>
          </div>
        )}

        {/* Action Buttons */}
        <div className="action-buttons" style={{
          display: 'flex',
          gap: '1.5rem',
          justifyContent: 'center',
          flexWrap: 'wrap'
        }}>
          <button
            onClick={handleSaveReview}
            disabled={saving || saved || !getAuthenticatedUser()}
            className="pulse-badge"
            style={{
              padding: '1rem 2rem',
              fontSize: '1rem',
              fontWeight: '700',
              border: 'none',
              borderRadius: '25px',
              cursor: saved || saving || !getAuthenticatedUser() ? 'not-allowed' : 'pointer',
              background: saved 
                ? '#22c55e' 
                : saving 
                  ? '#6b7280'
                  : !getAuthenticatedUser()
                    ? '#6b7280'
                    : 'linear-gradient(135deg, #8b5cf6, #ec4899)',
              color: 'white',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '0.5rem',
              transition: 'all 0.3s ease',
              opacity: (saving || !getAuthenticatedUser()) ? 0.6 : 1,
              boxShadow: saved ? 'none' : `
                10px 10px 20px rgba(139, 92, 246, 0.3),
                -10px -10px 20px rgba(255, 255, 255, 0.1)
              `
            }}
          >
            {saved ? '✅ Saved!' : saving ? '⏳ Saving...' : '💾 Save Review (+10 pts)'}
          </button>

          <button
            onClick={() => setShowShareModal(true)}
            style={{
              padding: '1rem 2rem',
              fontSize: '1rem',
              fontWeight: '700',
              border: '2px solid var(--neuro-text-accent, #667eea)',
              borderRadius: '25px',
              background: 'transparent',
              color: 'var(--neuro-text-accent, #667eea)',
              cursor: 'pointer',
              transition: 'all 0.3s ease',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              boxShadow: `
                8px 8px 16px var(--neuro-shadow-dark, rgba(0,0,0,0.2)),
                -8px -8px 16px var(--neuro-shadow-light, rgba(255,255,255,0.9))
              `
            }}
            onMouseOver={(e) => {
              e.target.style.background = 'var(--neuro-text-accent, #667eea)';
              e.target.style.color = 'white';
            }}
            onMouseOut={(e) => {
              e.target.style.background = 'transparent';
              e.target.style.color = 'var(--neuro-text-accent, #667eea)';
            }}
          >
            📤 Share Review
          </button>

          <button
            onClick={onStartOver}
            style={{
              padding: '1rem 2rem',
              fontSize: '1rem',
              fontWeight: '700',
              border: '2px solid var(--neuro-text-secondary, #5a6c7d)',
              borderRadius: '25px',
              background: 'transparent',
              color: 'var(--neuro-text-secondary, #5a6c7d)',
              cursor: 'pointer',
              transition: 'all 0.3s ease',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              boxShadow: `
                8px 8px 16px var(--neuro-shadow-dark, rgba(0,0,0,0.2)),
                -8px -8px 16px var(--neuro-shadow-light, rgba(255,255,255,0.9))
              `
            }}
            onMouseOver={(e) => {
              e.target.style.background = 'var(--neuro-text-secondary, #5a6c7d)';
              e.target.style.color = 'white';
            }}
            onMouseOut={(e) => {
              e.target.style.background = 'transparent';
              e.target.style.color = 'var(--neuro-text-secondary, #5a6c7d)';
            }}
          >
            🔄 Leave Another Review
          </button>
        </div>
      </div>

      <ShareModal />
    </div>
  );
};

export default ReviewAnalysis;